// Generates $CODEX_HOME/config.toml.
//
// The Claude engine has an analogue: yoda.js writes .claude/settings.json from
// the sandbox setting on every boot. This is the same idea for Codex — the file
// is generated, never hand-edited, so an operator's stale copy can't silently
// change how the agent behaves.

import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

/**
 * Big enough for the assembled persona.
 *
 * Codex TRUNCATES the instructions file at this many bytes, silently. A real
 * workspace's flattened persona is already past 50KB before the operator's own
 * memory and identity documents are counted, and MEMORY.md grows over time — so
 * the default would cut the persona off mid-document and the only symptom would
 * be an agent that half-remembers who it is.
 */
export const PROJECT_DOC_MAX_BYTES = 512 * 1024;

/**
 * Render the config file's contents.
 *
 * @param {object} [opts]
 * @param {string} [opts.sandboxMode]  'danger-full-access' | 'workspace-write' | 'read-only'
 * @returns {string}
 */
export function renderConfigToml({ sandboxMode = 'danger-full-access' } = {}) {
  return `# Generated by yodacode. Do not edit — rewritten on every start.
#
# The CONTAINER is the security boundary here, not the engine's sandbox: the
# agent runs as an unprivileged user with no service credentials, and reaches
# every external API through the broker. Codex's own sandbox is therefore set
# wide, exactly as the Claude engine runs with permissions accepted — a second,
# narrower boundary inside the container would only break the agent's own tools
# without protecting anything the container does not already protect.
sandbox_mode = "${sandboxMode}"

# Nobody is at a terminal to answer a prompt. Without this the agent stops and
# waits for an approval that can never arrive, which presents as a hang.
approval_policy = "never"

# Keep the credential in $CODEX_HOME/auth.json rather than an OS keyring: there
# is no keyring in the container, and 'auto' would fall back silently.
cli_auth_credentials_store = "file"

# The persona is assembled into one file because this engine has no @-imports.
# It is large, and the default limit truncates it without saying so.
project_doc_max_bytes = ${PROJECT_DOC_MAX_BYTES}
`;
}

/**
 * Write config.toml into CODEX_HOME, creating the directory if needed.
 * @returns {{path: string, bytes: number}}
 */
export function writeConfigToml({ codexHome, sandboxMode } = {}) {
  const home = codexHome || process.env.CODEX_HOME
    || path.join(process.env.HOME || '/root', '.codex');
  mkdirSync(home, { recursive: true });
  const file = path.join(home, 'config.toml');
  const text = renderConfigToml({ sandboxMode });
  writeFileSync(file, text);
  return { path: file, bytes: Buffer.byteLength(text, 'utf8') };
}
