// Read/merge/write .env files.

import fs from 'node:fs';
import path from 'node:path';

export function readEnv(envPath) {
  if (!fs.existsSync(envPath)) return {};
  const out = {};
  for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#') || !trimmed.includes('=')) continue;
    const [k, ...rest] = trimmed.split('=');
    out[k.trim()] = rest.join('=');
  }
  return out;
}

export function writeEnv(envPath, vars) {
  const lines = ['# YodaCode — generated by install.js', ''];
  for (const [k, v] of Object.entries(vars)) {
    lines.push(`${k}=${v}`);
  }
  fs.writeFileSync(envPath, lines.join('\n') + '\n');
  fs.chmodSync(envPath, 0o600);
}

export function mergeEnv(envPath, newVars) {
  const existing = readEnv(envPath);
  const merged = { ...existing, ...newVars };
  writeEnv(envPath, merged);
  return merged;
}
